"""add_contact_info_to_user

Revision ID: 06e170327118
Revises: eae27beaa10f
Create Date: 2026-03-29 16:31:27.429123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e170327118'
down_revision: Union[str, Sequence[str], None] = 'eae27beaa10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('adresse', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('code_postal', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('ville', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_naissance', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('lieu_naissance', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('users_manager_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_manager_id_fkey'), 'users', 'users', ['manager_id'], ['id'])
    op.drop_column('users', 'lieu_naissance')
    op.drop_column('users', 'date_naissance')
    op.drop_column('users', 'ville')
    op.drop_column('users', 'code_postal')
    op.drop_column('users', 'adresse')
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
