"""initial

Revision ID: 4268c3d89645
Revises: 
Create Date: 2026-03-04 10:16:31.077032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4268c3d89645'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sous_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=500), nullable=False),
    sa.Column('tarif', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=100), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('sous_mission_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sous_mission_id'], ['sous_missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sous_mission_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sous_mission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sous_mission_id'], ['sous_missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'sous_mission_id')
    )
    op.drop_index(op.f('ix_declaration_lines_declaration_id'), table_name='declaration_lines')
    op.drop_index(op.f('ix_declaration_lines_mission_id'), table_name='declaration_lines')
    op.drop_table('declaration_lines')
    op.add_column('declarations', sa.Column('site', sa.Enum('lyon_est', 'lyon_sud', name='site'), nullable=False))
    op.add_column('declarations', sa.Column('programme', sa.Enum('pass_', 'las1', 'las2', name='programme'), nullable=False))
    op.add_column('declarations', sa.Column('mois', sa.Integer(), nullable=False))
    op.add_column('declarations', sa.Column('annee', sa.Integer(), nullable=False))
    op.add_column('declarations', sa.Column('statut', sa.Enum('brouillon', 'soumise', 'validee', name='statutdeclaration'), nullable=False))
    op.add_column('declarations', sa.Column('commentaire_admin', sa.String(length=500), nullable=True))
    op.add_column('declarations', sa.Column('soumise_le', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_declarations_status'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_user_id'), table_name='declarations')
    op.drop_constraint(op.f('uq_declaration_user_month_year'), 'declarations', type_='unique')
    op.drop_constraint(op.f('declarations_user_id_fkey'), 'declarations', type_='foreignkey')
    op.create_foreign_key(None, 'declarations', 'users', ['user_id'], ['id'])
    op.drop_column('declarations', 'month')
    op.drop_column('declarations', 'rejection_comment')
    op.drop_column('declarations', 'year')
    op.drop_column('declarations', 'status')
    op.drop_column('declarations', 'submitted_at')
    op.add_column('missions', sa.Column('titre', sa.String(length=500), nullable=False))
    op.add_column('missions', sa.Column('ordre', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('missions', sa.Column('resp_only', sa.Boolean(), nullable=False))
    op.add_column('missions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_missions_title'), table_name='missions')
    op.drop_column('missions', 'title')
    op.drop_column('missions', 'rate')
    op.drop_column('missions', 'category')
    op.drop_column('missions', 'unit')
    op.add_column('users', sa.Column('nom', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('prenom', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('adresse', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('code_postal', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('ville', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('annee', sa.Enum('p2', 'd1', 'd2', name='annee'), nullable=True))
    op.add_column('users', sa.Column('profil_complete', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'filiere',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('medecine', 'pharmacie', 'maieutique', 'odontologie', 'kinesitherapie', name='filiere'),
               existing_nullable=True)
    op.alter_column('users', 'matiere',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'matiere',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('users', 'filiere',
               existing_type=sa.Enum('medecine', 'pharmacie', 'maieutique', 'odontologie', 'kinesitherapie', name='filiere'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'profil_complete')
    op.drop_column('users', 'annee')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'ville')
    op.drop_column('users', 'code_postal')
    op.drop_column('users', 'adresse')
    op.drop_column('users', 'prenom')
    op.drop_column('users', 'nom')
    op.add_column('missions', sa.Column('unit', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('missions', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('missions', sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('missions', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_missions_title'), 'missions', ['title'], unique=True)
    op.drop_column('missions', 'created_at')
    op.drop_column('missions', 'resp_only')
    op.drop_column('missions', 'is_active')
    op.drop_column('missions', 'ordre')
    op.drop_column('missions', 'titre')
    op.add_column('declarations', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('declarations', sa.Column('status', postgresql.ENUM('BROUILLON', 'SOUMISE', 'VALIDEE_INTERMEDIAIRE', 'VALIDE_SITE', 'VALIDEE_FINALE', name='declarationstatus'), autoincrement=False, nullable=False))
    op.add_column('declarations', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('declarations', sa.Column('rejection_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('declarations', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'declarations', type_='foreignkey')
    op.create_foreign_key(op.f('declarations_user_id_fkey'), 'declarations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_declaration_user_month_year'), 'declarations', ['user_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_declarations_user_id'), 'declarations', ['user_id'], unique=False)
    op.create_index(op.f('ix_declarations_status'), 'declarations', ['status'], unique=False)
    op.drop_column('declarations', 'soumise_le')
    op.drop_column('declarations', 'commentaire_admin')
    op.drop_column('declarations', 'statut')
    op.drop_column('declarations', 'annee')
    op.drop_column('declarations', 'mois')
    op.drop_column('declarations', 'programme')
    op.drop_column('declarations', 'site')
    op.create_table('declaration_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('declaration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], name=op.f('declaration_lines_declaration_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('declaration_lines_mission_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('declaration_lines_pkey'))
    )
    op.create_index(op.f('ix_declaration_lines_mission_id'), 'declaration_lines', ['mission_id'], unique=False)
    op.create_index(op.f('ix_declaration_lines_declaration_id'), 'declaration_lines', ['declaration_id'], unique=False)
    op.drop_table('user_sous_mission_permissions')
    op.drop_table('lignes_declaration')
    op.drop_table('sous_missions')
    # ### end Alembic commands ###
