"""v3_hierarchy_and_students

Revision ID: eae27beaa10f
Revises: 0001_init
Create Date: 2026-03-29 15:31:56.650551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae27beaa10f'
down_revision: Union[str, Sequence[str], None] = '0001_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('declarations_user_id_fkey'), 'declarations', type_='foreignkey')
    op.create_foreign_key(None, 'declarations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'profil_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'code_postal')
    op.drop_column('users', 'ville')
    op.drop_column('users', 'adresse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('adresse', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ville', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('code_postal', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'profil_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'manager_id')
    op.drop_constraint(None, 'declarations', type_='foreignkey')
    op.create_foreign_key(op.f('declarations_user_id_fkey'), 'declarations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
